tq_extjs_application_bootstrap:
    path:      /bootstrap-{build}.js
    defaults:
        _controller: tq_extjs.controller:bootstrapAction
        _format: js
    requirements:
        build:  \w+

tq_extjs_application_manifest:
    path:      /manifest-{build}.json
    defaults:
        _controller: tq_extjs.controller:manifestAction
        _format: json
    requirements:
        build:  \w+

tq_extjs_application_appcache:
    path:      /cache-{build}.appcache
    defaults:
        _controller: tq_extjs.controller:appCacheAction
    requirements:
        build:  \w+
