tq_extjs_application_bootstrap:
    path:      /{build}/bootstrap.js
    defaults:
        _controller: tq_extjs.controller:bootstrapAction
        _format: js
    requirements:
        build:  \w+

tq_extjs_application_manifest:
    path:      /{build}/manifest.json
    defaults:
        _controller: tq_extjs.controller:manifestAction
        _format: json
    requirements:
        build:  \w+

tq_extjs_application_appcache:
    path:      /{build}/cache.appcache
    defaults:
        _controller: tq_extjs.controller:appCacheAction
    requirements:
        build:  \w+
